<ul>
    <li>bharath</li>
    <li>Dimple</li>
    <li>jashwanth</li>
    <li>madhuri</li>
    <li>manoj</li>
    <li>pavan</li>
    <li>pavani</li>
    <li>rathayya</li>
    <li>shavali</li>
    <li>sireesha</li>
    <li>sudheer</li>
    <li>suhel</li>
    <li>tharun</li>
    <li>varun</li>
    <li>basavaraj</li>
</ul>